# Generated by Django 4.1.7 on 2023-02-20 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import utils.estate_code_generator
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estate_name', models.CharField(max_length=200, unique=True)),
                ('estate_profile_image', models.ImageField(null=True, upload_to='estate/')),
                ('estate_address', models.CharField(max_length=400, unique=True)),
                ('estate_country', django_countries.fields.CountryField(max_length=2)),
                ('public_id', models.CharField(default=utils.estate_code_generator.generate_short_id, max_length=15, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
