# Generated by Django 4.1.7 on 2023-02-21 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='estate_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='estate_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='estate_address',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='estate_profile_image',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='member',
        ),
        migrations.AddField(
            model_name='estate',
            name='location',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='estate/'),
        ),
    ]
