# Generated by Django 4.1.7 on 2023-02-23 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_rename_estate_country_estate_country_and_more'),
        ('Authentication', '0002_rename_is_user_user_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.CharField(max_length=500)),
                ('estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estate.estate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
